classes:
- system.linux.system.repo.tcp_salt
- system.openssh.client.lab
- system.salt.master.pkg
- system.salt.minion.ca.salt_master
- system.salt.minion.cert.k8s_server
- system.salt.master.api
- system.reclass.storage.salt
- cluster.emdb_kube.kubernetes.control
- cluster.emdb_kube
parameters:
  _param:
    salt_master_base_environment: prd
    reclass_data_repository: "https://github.com/cznewt/k8s-salt-model.git"
    reclass_data_revision: master
    reclass_config_master: ${_param:infra_config_address}
    single_address: ${_param:infra_config_address}
    salt_master_host: ${_param:infra_config_address}
    linux_system_codename: xenial
    keepalived_vip_priority: 103
  reclass:
    storage:
      node:
        kubernetes_control_node02:
          name: ${_param:kubernetes_control_node02_hostname}
          domain: ${_param:cluster_domain}
          classes:
          - cluster.${_param:cluster_name}.kubernetes.control
          params:
            salt_master_host: ${_param:reclass_config_master}
            linux_system_codename: xenial
            single_address: ${_param:kubernetes_control_node02_address}
            keepalived_vip_priority: 102
        kubernetes_control_node03:
          name: ${_param:kubernetes_control_node03_hostname}
          domain: ${_param:cluster_domain}
          classes:
          - cluster.${_param:cluster_name}.kubernetes.control
          params:
            salt_master_host: ${_param:reclass_config_master}
            linux_system_codename: xenial
            single_address: ${_param:kubernetes_control_node03_address}
            keepalived_vip_priority: 101
        kubernetes_compute_node01:
          name: ${_param:kubernetes_compute_node01_hostname}
          domain: ${_param:cluster_domain}
          classes:
          - cluster.${_param:cluster_name}.kubernetes.compute
          params:
            salt_master_host: ${_param:reclass_config_master}
            linux_system_codename: xenial
            single_address: ${_param:kubernetes_compute_node01_single_address}
        kubernetes_compute_node02:
          name: ${_param:kubernetes_compute_node02_hostname}
          domain: ${_param:cluster_domain}
          classes:
          - cluster.${_param:cluster_name}.kubernetes.compute
          params:
            salt_master_host: ${_param:reclass_config_master}
            linux_system_codename: xenial
            single_address: ${_param:kubernetes_compute_node02_single_address}
        gateway_node01:
          name: gtw01
          domain: ${_param:cluster_domain}
          classes:
          - cluster.${_param:cluster_name}.kubernetes.gateway
          params:
            salt_master_host: 185.22.99.7
            linux_system_codename: jessie
